dist: xenial
language: bash
services:
- docker
addons:
  snaps:
  - name: snapcraft
    confinement: classic
before_install:
- openssl aes-256-cbc -K $encrypted_733e17776623_key -iv $encrypted_733e17776623_iv -in snap_token.enc -out snap_token -d
script:
# build
- docker run -v $(pwd)/snap:/root/snap -v $(pwd):/root/output -w $(pwd) snapcore/snapcraft:stable sh -c "cd /root && apt update && snapcraft && cp latexml_*_amd64.snap ./output/"
# install
- sudo snap install *.snap --devmode
# test
- latexml --VERSION || echo "Expected exit code 1"
- latexml --dest=test.xml test.tex
deploy:
- provider: script
  skip_cleanup: true
  script: ./.travis/deploy.sh
  on:
    tags: true
    branch: master
