dist: xenial
services: [docker]
addons:
  apt:
    update: true
    packages:
      - snapd
      - snapcraft
script:
  - docker run -v $(pwd)/snap:/root/snap -v $(pwd):/root/output -w $(pwd) snapcore/snapcraft:stable sh -c "cd /root && apt update && snapcraft && cp latexml_*_amd64.snap ./output/docker.snap"
  - sudo snap install *.snap --devmode
  - latexml --VERSION || echo "Expected exit code 1"
  - latexml --dest=test.xml test.tex
deploy:
  skip_cleanup: true
  provider: script
  script:
  - cat snap_token | snapcraft login --with -
  - snapcraft push --release=stable metanorma_*_amd64.snap
  on:
    tags: true
    branch: master
after_success:
- openssl aes-256-cbc -K $encrypted_733e17776623_key -iv $encrypted_733e17776623_iv -in .snapcraft/travis_snapcraft.cfg -out .snapcraft/snapcraft.cfg -d
