dist: xenial
services: [docker]
language: bash
addons:
  apt:
    update: true
    packages:
      - snapd
      - snapcraft
script:
  # build
  - docker run -v $(pwd)/snap:/root/snap -v $(pwd):/root/output -w $(pwd) snapcore/snapcraft:stable sh -c "cd /root && apt update && snapcraft && cp latexml_*_amd64.snap ./output/docker.snap"
  # install
  - sudo snap install *.snap --devmode
  # test
  - latexml --VERSION || echo "Expected exit code 1"
  - latexml --dest=test.xml test.tex
after_success:
  - openssl aes-256-cbc -K $encrypted_733e17776623_key -iv $encrypted_733e17776623_iv -in .snapcraft/travis_snapcraft.cfg -out .snapcraft/snapcraft.cfg -d
deploy:
  - provider: script
    skip_cleanup: true
    provider: script
    script:
      - snapcraft push --release=stable latexml_*_amd64.snap
    script: ./.travis/deploy.sh
    on:
      tags: true
      branch: master
