= LaTeXML Snap Package

image:https://github.com/metanorma/latexml-snap/workflows/main/badge.svg["Build Status", link="https://github.com/metanorma/latexml-snap/actions?query=workflow%3Amain"]
image:https://snapcraft.io/latexml/badge.svg["Snap Version", link="https://snapcraft.io/latexml"]

== Purpose

The LaTeXML snap package is a self-contained package that includes all the
dependencies required to run LaTeXML, a LaTeX to XML/HTML/MathML converter.
It is designed to be easy to install and use, and provides a consistent
environment for running LaTeXML across different Linux distributions.

LaTeXML is developed by NIST and transforms TeX/LaTeX into XML/HTML/MathML
formats. For more information, see https://dlmf.nist.gov/LaTeXML/.


== What is Snapcraft?

Snapcraft is a tool to build, package and distribute software for Linux
distributions. It is a cross-platform package manager that allows developers
to create and distribute software packages that can run on any Linux
distribution that supports the snap format.


== Installation

The released LaTeXML snap package is located at Snapcraft:
https://snapcraft.io/latexml[LaTeXML snap].

[source,sh]
----
sudo snap install latexml
----


== Supported platforms

The snap package is built for the following architectures:

* amd64
* arm64
* armhf
* ppc64el
* s390x


== Decisions

* The packages are built using `ubuntu-24.04` runners with QEMU for
  cross-compilation on non-native architectures.

* The base is `core24` (Ubuntu 24.04 LTS).

* The containers used for building snap packages are vanilla GitHub Action
  Runners because the official https://hub.docker.com/r/snapcore/snapcraft/[snapcraft containers]
  lack arm64 versions, and are severely outdated from 2021.


== Building the package

On Linux:

[source,sh]
----
# Enter the root directory of this repo
snapcraft snap
----

Via Docker:

WARNING: This is not working on macOS.

[source,sh]
----
docker run --rm -it --privileged -v $PWD:/data -w /data ghcr.io/canonical/snapcraft-container:core24
----

NOTE: Snapcraft relies on `snapd` which requires privileged containers.


== Testing the package

If you are on macOS you can install snap to any of your multipass instances with:

[source,sh]
----
multipass transfer latexml_*_amd64.snap ${instance-name}:/home/multipass
multipass shell ${instance-name}
sudo snap install --devmode latexml_*_amd64.snap
----

After this the snap is ready to use.


=== Testing uninstallation

Execute the following command to uninstall LaTeXML.

[source,sh]
----
sudo snap remove latexml
----

After executing the uninstall ensure that the `latexml` executable is no
longer found.

You can also try running `latexml --VERSION` from the command-line to see if it is
still installed.


== Generating the snapcraft token

We use the https://github.com/canonical/action-publish[canonical/action-publish]
GitHub Actions workflow to publish our snaps.

Every so often, we need to update the token used to publish the snap as the old
one expires.

Run the following Docker command to obtain credentials:

[source,sh]
----
$ docker run -v $PWD:/export -it snapcore/snapcraft:stable snapcraft export-login \
  --snaps=latexml \
  --acls package_access,package_push,package_update,package_release \
  /export/exported.txt

Enter your Ubuntu One e-mail address and password.
If you do not have an Ubuntu One account, you can create one at https://snapcraft.io/account
Email:
Password:

We strongly recommend enabling multi-factor authentication: https://help.ubuntu.com/community/SSO/FAQs/2FA

Login successfully exported to '/export/exported.txt'. This can now be used with

    snapcraft login --with /export/exported.txt

to log in to this account with no password and have these
capabilities:

snaps:       ['latexml']
channels:    No restriction
permissions: ['package_access', 'package_push', 'package_update', 'package_release']
expires:     ...

This exported login is not encrypted. Do not commit it to version control!
----

Then on your own machine, run the following command to read the file:

[source,sh]
----
$ cat exported.txt
[login.ubuntu.com]
macaroon = AABBB...
unbound_discharge = AABBB...
email = ...
----

NOTE: In this repository, the exported login `AABBB...==` value is placed in
GitHub Actions' secret named `METANORMA_SNAPCRAFT_LATEXML_TOKEN`.


== Release workflow (`main.yml`)

This repository uses GitHub Actions workflows to automate the building and
releasing of snap packages to different channels.

The main workflow automatically handles releases based on git events:

* **Main branch pushes**: Automatically releases to the `edge` and `beta` channels
* **Version tags**: Automatically releases to `candidate` channel and promotes
  to `stable` for non-pre-release tags (e.g., `v0.8.8`)

The workflow follows Snapcraft best practices by uploading the snap package once
to the candidate/edge channel, then promoting the same revision to the stable
channel using the `snapcraft release` command.


== Manual promotion

=== General

For cases where you need to promote an existing revision to the stable channel
without rebuilding, use the manual promotion workflow.

=== Finding revision numbers

To find available revision numbers, you can:

* Check the output of previous workflow runs in the GitHub Actions logs
* Use the Snapcraft dashboard at https://snapcraft.io/latexml/releases
* Run the following command locally (requires snapcraft login):

[source,sh]
----
snapcraft login --with /export/exported.txt
snapcraft list-revisions latexml
----


=== Manually promoting a version to stable using the workflow

. Navigate to the GitHub Actions tab in the repository
. Select the "promote-to-stable" workflow
. Click "Run workflow"
. Enter the revision number you want to promote to stable (or leave empty to
  auto-detect from candidate/beta)
. Click "Run workflow" to execute

[example]
====
To promote revision 42 to stable:

. Go to https://github.com/metanorma/latexml-snap/actions
. Click on "promote-to-stable" workflow
. Click "Run workflow" button
. Enter `42` in the revision field
. Click "Run workflow"
====


=== Manually promoting revisions

For cases where you need to promote an existing revision to the stable channel
without rebuilding, run the following local commands (e.g. through Docker).

[source,sh]
----
snapcraft login --with /export/exported.txt
snapcraft release latexml <revision> stable
----


=== Use cases for manual promotion

The manual promotion workflow is useful for:

* **Hotfix scenarios**: Promote a specific tested revision without waiting for
  the full build pipeline
* **Rollback**: Promote an older revision back to stable if issues are
  discovered
* **Recovery**: When automated promotion fails and needs manual intervention
* **Testing**: Promote specific revisions for validation purposes


== Copyright & License

Copyright Ribose. Licensed under the Ribose 2-clause BSD license.
