name: latexml
base: core18
version: '0.8.4'
summary: A LaTeX to XML/HTML/MathML Converter
description: |
  In the process of developing the Digital Library of Mathematical Functions, NIST had needed a means of transforming the LaTeX sources of our material into XML which would be used for further manipulations, rearrangements and construction of the web site. In particular, a true ‘Digital Library’ should focus on the semantics of the material, and so NIST should convert the mathematical material into both content and presentation MathML. At the time, there found no software suitable to our needs, so NIST began development of LaTeXML in-house.

grade: stable
confinement: strict

parts:
  latexml:
    plugin: cpanm
    cpanm-packages: [LaTeXML@0.8.4]
    build-packages: [libxml2-dev, libxslt1-dev, libicu-dev, zlib1g-dev]
    stage-packages: [libxml2, libxslt1.1, zlib1g]
    override-stage: |
      snapcraftctl stage
      chmod 0755 ./usr/local/share/sgml
      chmod 0755 ./usr/local/share/sgml/declaration
      chmod 0755 ./usr/local/share/sgml/dtd
      chmod 0755 ./usr/local/share/sgml/entities
      chmod 0755 ./usr/local/share/sgml/misc
      chmod 0755 ./usr/local/share/sgml/stylesheet
      chmod 0755 ./usr/local/share/xml
      chmod 0755 ./usr/local/share/xml/declaration
      chmod 0755 ./usr/local/share/xml/entities
      chmod 0755 ./usr/local/share/xml/misc
      chmod 0755 ./usr/local/share/xml/schema
apps:
  latexml:
    environment:
      LC_ALL: "C.UTF-8"
    command: bash $SNAP/usr/bin/perl5lib.sh $SNAP/usr/local/bin/latexml
    plugs:
      - home
      - network
  c:
    environment:
      LC_ALL: "C.UTF-8"
    command: bash $SNAP/usr/bin/perl5lib.sh $SNAP/usr/local/bin/latexmlc
    plugs:
      - home
      - network
  find:
    environment:
      LC_ALL: "C.UTF-8"
    command: bash $SNAP/usr/bin/perl5lib.sh $SNAP/usr/local/bin/latexmlfind
    plugs:
      - home
      - network
  math:
    environment:
      LC_ALL: "C.UTF-8"
    command: bash $SNAP/usr/bin/perl5lib.sh $SNAP/usr/local/bin/latexmlmath
    plugs:
      - home
      - network
  post:
    environment:
      LC_ALL: "C.UTF-8"
    command: bash $SNAP/usr/bin/perl5lib.sh $SNAP/usr/local/bin/latexmlpost
    plugs:
      - home
      - network