name: ubuntu

on:
  push:
    branches: [ main ]
    tags: [ v* ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build LaTeXML snap
    runs-on: ubuntu-latest
    container:
      image: snapcore/snapcraft:stable
    steps:
      - uses: actions/checkout@v4
      - name: Snapcraft setup
        run: |
          sudo apt-get update
          sudo apt-get install -y squashfs-tools python3
          snapcraft --version
      - name: Build snap
        run: |
          snapcraft snap --output latexml.snap
      - name: Fix snap
        run: |
          unsquashfs latexml.snap
          sudo chmod -R g-s ./squashfs-root
          snapcraft pack squashfs-root --output latexml_fixed.snap
      - uses: actions/upload-artifact@v4
        with:
          name: latexml-snap
          path: latexml_fixed.snap

  test:
    name: Test LaTeXML snap
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Snapcraft setup
        run: |
          sudo apt update
          sudo apt install -y snapd
      - uses: actions/download-artifact@v4
        with:
          name: latexml-snap
          path: ./snap
      - name: Install snap
        run: |
          sudo snap install snap/latexml_fixed.snap --devmode
      - name: Test snap
        run: |
          latexml --VERSION || echo "Expected exit code 1"
          latexml --dest=test.xml test.tex

  release-stable:
    if: startsWith(github.ref, 'refs/tags/v') && !endsWith(github.ref, 'pre')
    name: Release edge snap
    needs: test
    runs-on: ubuntu-latest
    container:
      image: snapcore/snapcraft:stable
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: latexml-snap
          path: ./snap
      - name: Push to snapcraft.io
        env:
          SNAPCRAFT_TOKEN: ${{ secrets.METANORMA_SNAPCRAFT_TOKEN }}
        run: |
          echo "${SNAPCRAFT_TOKEN}" > .snapcraft_token
          snapcraft login --with .snapcraft_token
          snapcraft push --release=stable snap/latexml_fixed.snap

  release-edge:
    if: github.ref == 'refs/heads/master'
    name: Release edge snap
    needs: test
    runs-on: ubuntu-latest
    container:
      image: snapcore/snapcraft:stable
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: latexml-snap
          path: ./snap
      - name: Push to snapcraft.io
        env:
          SNAPCRAFT_TOKEN: ${{ secrets.METANORMA_SNAPCRAFT_TOKEN }}
        run: |
          echo "${SNAPCRAFT_TOKEN}" > .snapcraft_token
          snapcraft login --with .snapcraft_token
          snapcraft push --release=edge snap/latexml_fixed.snap

  release-candidate:
    if: startsWith(github.ref, 'refs/tags/v') && endsWith(github.ref, 'pre')
    name: Release stable snap
    needs: test
    runs-on: ubuntu-latest
    container:
      image: snapcore/snapcraft:stable
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: latexml-snap
          path: ./snap
      - name: Push to snapcraft.io
        env:
          SNAPCRAFT_TOKEN: ${{ secrets.METANORMA_SNAPCRAFT_TOKEN }}
        run: |
          echo "${SNAPCRAFT_TOKEN}" > .snapcraft_token
          snapcraft login --with .snapcraft_token
          snapcraft push --release=candidate snap/latexml_fixed.snap
