name: ubuntu

on:
  push:
    tags:
      - v*

jobs:
  deploy:
    name: Test on Ruby ${{ matrix.ruby }} Ubuntu
    runs-on: ubuntu-latest
    container:
      image: snapcore/snapcraft
    steps:
      - uses: actions/checkout@master
      - name: Snapcraft setup
        run: |
          sudo apt update
          sudo apt install -y snapd
          sudo apt-get update
          sudo apt-get install -y squashfs-tools python3
          snapcraft --version
      - name: Build snap
        run: |
          snapcraft snap --output latexml.snap
      - name: Fix snap
        run: |
          unsquashfs latexml.snap
          sudo chmod -R g-s ./squashfs-root
          snapcraft pack squashfs-root --output latexml_fixed.snap
      - name: Install snap
        run: |
          sudo snap install latexml_fixed.snap --devmode
      - name: Test snap
        run: |
          latexml --VERSION || echo "Expected exit code 1"
      - name: Push to snapcraft.io
        run: |
          echo "${{ secrets.snapcraft_token }}" > .snapcraft/snapcraft.cfg
          snapcraft login --with .snapcraft/snapcraft.cfg
          snapcraft push --release=beta latexml_fixed.snap
