name: release-tag

on:
  workflow_dispatch:
    inputs:
      next_version:
        description: |
          Next release version.
        required: true

jobs:
  push-tag:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.METANORMA_CI_PAT_TOKEN }}

    - run: echo SNAP_VERSION=${{ github.event.inputs.next_version }} >> ${GITHUB_ENV}

    - run: echo -n ${SNAP_VERSION} > VERSION

    - name: Push commit and tag
      run: |
        git config --global user.name "metanorma-ci"
        git config --global user.email "metanorma-ci@users.noreply.github.com"
        git add VERSION
        git commit -m "Bump version to ${SNAP_VERSION}"
        git tag v${SNAP_VERSION}
        git push origin HEAD:${GITHUB_REF} --tags
